version: "3.9"
services:
  db1:
    image: postgres
    container_name: db1
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cd_auth
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./db/shortcut/data:/var/lib/postgresql/data
    restart: always
  auth:
    network_mode: host
    build:
      context: .
      dockerfile: services/auth/Dockerfile
    environment:
      - JDBC_URL=jdbc:postgresql://db1:5432/cd_auth
      - JDBC_USERNAME=postgres
      - JDBC_PASSWORD=1234
      - JDBC_DRIVER=org.postgresql.Driver
    ports:
      - "127.0.0.1:8080:8080"
    container_name: auth
    depends_on:
      - db1
  db2:
    image: postgres
    container_name: db2
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cd_desc
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./db/shortcut/data:/var/lib/postgresql/data
    restart: always
  desc:
    network_mode: host
    build:
      context: .
      dockerfile: services/desc/Dockerfile
    environment:
      - JDBC_URL=jdbc:postgresql://db2:5432/cd_desc
      - JDBC_USERNAME=postgres
      - JDBC_PASSWORD=1234
      - JDBC_DRIVER=org.postgresql.Driver
    ports:
      - "127.0.0.1:8080:8080"
    container_name: desc
    depends_on:
      - db2
  db3:
    image: postgres
    container_name: db3
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mock
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./db/shortcut/data:/var/lib/postgresql/data
    restart: always
  mock:
    network_mode: host
    build:
      context: .
      dockerfile: services/mock/Dockerfile
    environment:
      - JDBC_URL=jdbc:postgresql://db3:5432/mock
      - JDBC_USERNAME=postgres
      - JDBC_PASSWORD=1234
      - JDBC_DRIVER=org.postgresql.Driver
    ports:
      - "127.0.0.1:8080:8080"
    container_name: mock
    depends_on:
      - db3
  db4:
    image: postgres
    container_name: db4
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cd_notification
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./db/shortcut/data:/var/lib/postgresql/data
    restart: always
  notification:
    network_mode: host
    build:
      context: .
      dockerfile: services/notification/Dockerfile
    environment:
      - JDBC_URL=jdbc:postgresql://db4:5432/cd_notification
      - JDBC_USERNAME=postgres
      - JDBC_PASSWORD=1234
      - JDBC_DRIVER=org.postgresql.Driver
    ports:
      - "127.0.0.1:8080:8080"
    container_name: notification
    depends_on:
      - db4
  site:
    network_mode: host
    build:
      context: .
      dockerfile: services/site/Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    container_name: site
    depends_on:
      - auth
      - desc
      - mock
      - notification